# you must define the function BEFORE adding a subdirectories,
# otherwise the function will not be available
function(PrjAddLibs prj_name)

  if(TARGET SDL2::SDL2main)
    # It has an implicit dependency on SDL2 functions,
    # so it MUST be added before SDL2::SDL2 (or SDL2::SDL2-static)
    target_link_libraries(${prj_name} PRIVATE SDL2::SDL2main)
  endif()

  # not *nix systems
  if(TARGET SDL2::SDL2)
    target_link_libraries(${prj_name} PRIVATE SDL2::SDL2)
  endif()
  if(TARGET SDL2_image::SDL2_image)
    target_link_libraries(${prj_name} PRIVATE SDL2_image::SDL2_image)
  endif()
  if(TARGET SDL2_ttf::SDL2_ttf)
    target_link_libraries(${prj_name} PRIVATE SDL2_ttf::SDL2_ttf)
  endif()
  if(TARGET SDL2_mixer::SDL2_mixer)
    target_link_libraries(${prj_name} PRIVATE SDL2_mixer::SDL2_mixer)
  endif()
  if(TARGET SDL2_gfx::SDL2_gfx)
    target_link_libraries(${prj_name} PRIVATE SDL2_gfx::SDL2_gfx)
  endif()
  if(TARGET SDL2_net::SDL2_net)
    target_link_libraries(${prj_name} PRIVATE SDL2_net::SDL2_net)
  endif()

  # *nix systems
  if(TARGET PkgConfig::SDL2)
    target_link_libraries(${prj_name} PRIVATE PkgConfig::SDL2)
  endif()
  if(TARGET PkgConfig::SDL2_image)
    target_link_libraries(${prj_name} PRIVATE PkgConfig::SDL2_image)
  endif()
  if(TARGET PkgConfig::SDL2_ttf)
    target_link_libraries(${prj_name} PRIVATE PkgConfig::SDL2_ttf)
  endif()
  if(TARGET PkgConfig::SDL2_mixer)
    target_link_libraries(${prj_name} PRIVATE PkgConfig::SDL2_mixer)
  endif()
  if(TARGET PkgConfig::SDL2_gfx)
    target_link_libraries(${prj_name} PRIVATE PkgConfig::SDL2_gfx)
  endif()
  if(TARGET PkgConfig::SDL2_net)
    target_link_libraries(${prj_name} PRIVATE PkgConfig::SDL2_net)
  endif()

endfunction()
